version: 2
jobs:
   build:
         working_directory: ~/PaintApp

         docker:
           - image: circleci/openjdk:8-jdk-browsers

         steps:
           - checkout

           # Use dependencies from cache
           - restore_cache:
               key: jars-{{ checksum "build.gradle" }}
#               keys:
#                 - v1-PaintApp-{{ checksum "build.gradle" }}
#                 - v1-PaintApp-{{ .Branch }}

           - run:
               name: run build
               command: |
                  ./gradlew build

           # save the current dependencies state as a cache state
           - save_cache:
               key: jars-{{ checksum "build.gradle" }}
               paths:
                   - ~/.gradle

           # store test results from XML files from the build and use it to provide insights into the build.
           - store_test_results:
               path: build/test-results

           # store the jar produced
           - store_artifacts:
               path: build/libs/
               destination: artifact/
