version: 2
jobs:
   build:
         working_directory: ~/PaintApp

         docker:
           - image: circleci/openjdk:8-jdk-browsers

         steps:
           - checkout

           # Use dependencies from cache
           - restore_cache:
               key: jars-{{ checksum "build.gradle" }}
#               keys:
#                 - v1-PaintApp-{{ checksum "build.gradle" }}
#                 - v1-PaintApp-{{ .Branch }}

           - run:
               name: run build
               command: |
                  ./gradlew build

           # save the current dependencies state as a cache state
           - save_cache:
               key: jars-{{ checksum "build.gradle" }}
               paths:
                   - ~/.gradle

           # collect test metadata from XML files from the build and use it to provide insights into the build.
           - run:
               name: Save test results
               command: |
                 mkdir -p /tmp/junit/
                 find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} /tmp/junit/ \;
               when: always
           - store_test_results:
               path: /tmp/junit/

           # store the jar produced
           - store_artifacts:
               path: build/libs/
               destination: artifact/
