version: 2
jobs:
   build:
         working_directory: ~/PaintApp

         docker:
           - image: circleci/openjdk:8-jdk-browsers

         steps:
           - checkout

           # Use dependencies from cache
           - restore_cache:
               key: v1-PaintApp-{{ checksum "build.gradle" }}
#               keys:
#                 - v1-PaintApp-{{ checksum "build.gradle" }}
#                 - v1-PaintApp-{{ .Branch }}

           - run:
               name: run gradle
               command: |
                  ./gradlew build

           # collect test metadata from XML files from the build and use it to provide insights into the build.
           - run:
               name: Save test results
               command: |
                 mkdir -p $CIRCLE_TEST_REPORTS/junit/
                 find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
               when: always
           - store_test_results:
               path: $CIRCLE_TEST_REPORTS/junit/

           # save the current dependencies state as a cache state
           - save_cache:
               key: v1-PaintApp-{{ checksum "build.gradle" }}
               paths:
                   - /lib

           # store the jar produced
           - store_artifacts:
               path: build/libs/
               destination: artifact/
